DROP DATABASE IF EXISTS MarieTeam;
CREATE DATABASE MarieTeam;
USE MarieTeam;

DROP TABLE IF EXISTS Secteur ;
CREATE TABLE Secteur (idSecteur INT AUTO_INCREMENT NOT NULL,
nomSecteur VARCHAR(255),
PRIMARY KEY (idSecteur)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Reservation ;
CREATE TABLE Reservation (numRes INT NOT NULL,
nomRes VARCHAR(255),
adresse VARCHAR(255),
codePostal VARCHAR(5),
ville VARCHAR(255),
numTra INT,
PRIMARY KEY (numRes)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Periode ;
CREATE TABLE Periode (dateDeb DATE AUTO_INCREMENT NOT NULL,
dateFin DATE,
PRIMARY KEY (dateDeb)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Categorie ;
CREATE TABLE Categorie (lettre CHAR AUTO_INCREMENT NOT NULL,
libelleCat VARCHAR(255),
PRIMARY KEY (lettre)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Liaison ;
CREATE TABLE Liaison (code INT AUTO_INCREMENT NOT NULL,
distance FLOAT,
idSecteur INT,
idPort_Depart INT,
idPort_Arrivee INT,
PRIMARY KEY (code)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Port ;
CREATE TABLE Port (idPort INT AUTO_INCREMENT NOT NULL,
nomPort VARCHAR(255),
PRIMARY KEY (idPort)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Type ;
CREATE TABLE Type (idType INT AUTO_INCREMENT NOT NULL,
libelleType VARCHAR(255),
lettre CHAR,
PRIMARY KEY (idType)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Traversee ;
CREATE TABLE Traversee (numTra INT AUTO_INCREMENT NOT NULL,
date DATE,
heure TIME,
idBat INT,
code INT,
PRIMARY KEY (numTra)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Bateau ;
CREATE TABLE Bateau (idBat INT AUTO_INCREMENT NOT NULL,
nomBat VARCHAR(255),
PRIMARY KEY (idBat)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Enregistrer ;
CREATE TABLE Enregistrer (idType INT AUTO_INCREMENT NOT NULL,
numRes INT NOT NULL,
quantite INT,
PRIMARY KEY (idType,
 numRes)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Tarifer ;
CREATE TABLE Tarifer (dateDeb DATE AUTO_INCREMENT NOT NULL,
idType INT NOT NULL,
code INT NOT NULL,
tarif FLOAT,
PRIMARY KEY (dateDeb,
 idType,
 code)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Contenir ;
CREATE TABLE Contenir (lettre CHAR AUTO_INCREMENT NOT NULL,
idBat INT NOT NULL,
PRIMARY KEY (lettre,
 idBat)) ENGINE=InnoDB;

ALTER TABLE Reservation ADD CONSTRAINT FK_Reservation_numTra FOREIGN KEY (numTra) REFERENCES Traversee (numTra);
ALTER TABLE Liaison ADD CONSTRAINT FK_Liaison_idSecteur FOREIGN KEY (idSecteur) REFERENCES Secteur (idSecteur);
ALTER TABLE Liaison ADD CONSTRAINT FK_Liaison_idPort_Depart FOREIGN KEY (idPort_Depart) REFERENCES Port (idPort);
ALTER TABLE Liaison ADD CONSTRAINT FK_Liaison_idPort_Arrivee FOREIGN KEY (idPort_Arrivee) REFERENCES Port (idPort);
ALTER TABLE Type ADD CONSTRAINT FK_Type_lettre FOREIGN KEY (lettre) REFERENCES Categorie (lettre);
ALTER TABLE Traversee ADD CONSTRAINT FK_Traversee_idBat FOREIGN KEY (idBat) REFERENCES Bateau (idBat);
ALTER TABLE Traversee ADD CONSTRAINT FK_Traversee_code FOREIGN KEY (code) REFERENCES Liaison (code);
ALTER TABLE Enregistrer ADD CONSTRAINT FK_Enregistrer_idType FOREIGN KEY (idType) REFERENCES Type (idType);
ALTER TABLE Enregistrer ADD CONSTRAINT FK_Enregistrer_numRes FOREIGN KEY (numRes) REFERENCES Reservation (numRes);
ALTER TABLE Tarifer ADD CONSTRAINT FK_Tarifer_dateDeb FOREIGN KEY (dateDeb) REFERENCES Periode (dateDeb);
ALTER TABLE Tarifer ADD CONSTRAINT FK_Tarifer_idType FOREIGN KEY (idType) REFERENCES Type (idType);
ALTER TABLE Tarifer ADD CONSTRAINT FK_Tarifer_code FOREIGN KEY (code) REFERENCES Liaison (code);
ALTER TABLE Contenir ADD CONSTRAINT FK_Contenir_lettre FOREIGN KEY (lettre) REFERENCES Categorie (lettre);
ALTER TABLE Contenir ADD CONSTRAINT FK_Contenir_idBat FOREIGN KEY (idBat) REFERENCES Bateau (idBat);